# Generated by Django 6.1.1 on 2026-09-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silhouette', models.CharField(max_length=150)),
                ('colorway', models.CharField(max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sneakers/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], default='new', max_length=10)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist')], default='owned', max_length=10)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.sneaker')),
            ],
        ),
    ]
