# Generated by Django 6.1.1 on 2026-09-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectionitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='size',
            field=models.CharField(choices=[('3', 'UK 3'), ('3.5', 'UK 3.5'), ('4', 'UK 4'), ('4.5', 'UK 4.5'), ('5', 'UK 5'), ('5.5', 'UK 5.5'), ('6', 'UK 6'), ('6.5', 'UK 6.5'), ('7', 'UK 7'), ('7.5', 'UK 7.5'), ('8', 'UK 8'), ('8.5', 'UK 8.5'), ('9', 'UK 9'), ('9.5', 'UK 9.5'), ('10', 'UK 10'), ('10.5', 'UK 10.5'), ('11', 'UK 11'), ('11.5', 'UK 11.5'), ('12', 'UK 12'), ('12.5', 'UK 12.5'), ('13', 'UK 13'), ('13.5', 'UK 13.5'), ('14', 'UK 14'), ('14.5', 'UK 14.5'), ('15', 'UK 15')], max_length=4),
        ),
    ]
