# Generated by Django 6.1.1 on 2026-09-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collectionitem_price_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitem',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
